[tls]

[tls.stores]

[tls.stores.default]

[tls.stores.default.defaultCertificate]
certFile = "certs/cert.pem"
keyFile = "certs/key.pem"

[[tls.certificates]]
certFile = "certs/cert.misbrico.pem"
keyFile = "certs/key.misbrico.pem"
